### PR TITLE
Feature/robotiq review

### PR DESCRIPTION
**Pull request by athackst**
Hi @hongkai-dai @arshan

This is an old open PR that I have out there.  It should mostly follow ROS style guides and not Google.  Please look over and add feedback.  The robotiq repo was waiting on the license file attachment from me (included in this), but otherwise approved it already.  

--Allison

---
This change is [Reviewable](https://reviewable.io/reviews/athackst/robotiq/1)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
Reviewed 1 of 20 files at r1, 19 of 19 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[robotiq_s_model_control/include/robotiq_s_model_control/s_model_api.h, line 74 at r3](https://reviewable.io:443/reviews/athackst/robotiq/1#-KXgwGF35O8bSUvX-Z2Y:-KXgwGF35O8bSUvX-Z2Z:b-a712ci) ([raw file](https://github.com/athackst/robotiq/blob/6b5fc963f7b130fb793a8a31ae9538e50434ddb7/robotiq_s_model_control/include/robotiq_s_model_control/s_model_api.h#L74)):*
> ```objc
>     void getRaw(SModelClientBase::GripperInput &raw);
> 
>     void getCommandPos(double &posA, double &posB, double &posC, double &posS);
> ```

const method? Same for all getters. Also according to google style guide, all reference should be const https://google.github.io/styleguide/cppguide.html#Reference_Arguments, So the function signature should be
```
void getCommandPos(double* posA, double* posB, double* posC, double* posS) const;
```

---

*[robotiq_s_model_control/include/robotiq_s_model_control/s_model_api.h, line 110 at r3](https://reviewable.io:443/reviews/athackst/robotiq/1#-KXgxPjPqOnmb8XrJ5ZU:-KXgxPjPqOnmb8XrJ5ZV:b8bkb45) ([raw file](https://github.com/athackst/robotiq/blob/6b5fc963f7b130fb793a8a31ae9538e50434ddb7/robotiq_s_model_control/include/robotiq_s_model_control/s_model_api.h#L110)):*
> ```objc
>     value = value < std::numeric_limits<T>::min() ? std::numeric_limits<T>::min() : value;
>     value = value > std::numeric_limits<T>::max() ? std::numeric_limits<T>::max() : value;
>     return (T)value;
> ```

use `static_cast<T>(value)` according to google style guide https://google.github.io/styleguide/cppguide.html#Casting

---

*[robotiq_s_model_control/include/robotiq_s_model_control/s_model_hw_interface.h, line 56 at r3](https://reviewable.io:443/reviews/athackst/robotiq/1#-KXgyGrZIF4znA8-uW5C:-KXgyGrZIF4znA8-uW5D:b-w7z99r) ([raw file](https://github.com/athackst/robotiq/blob/6b5fc963f7b130fb793a8a31ae9538e50434ddb7/robotiq_s_model_control/include/robotiq_s_model_control/s_model_hw_interface.h#L56)):*
> ```objc
>     std::vector<double> j_cmd_pos_;
> 
>     boost::shared_ptr<SModelAPI> hw_driver_;
> ```

Why using `boost::shared_ptr` instead of `std::shared_ptr`?

---

*[robotiq_s_model_control/src/robotiq_s_model_control/s_model_can_client.cpp, line 33 at r3](https://reviewable.io:443/reviews/athackst/robotiq/1#-KXgz00OU32CdSt2GrDM:-KXgz00Ps-yXC-zHahCU:b-y890yi) ([raw file](https://github.com/athackst/robotiq/blob/6b5fc963f7b130fb793a8a31ae9538e50434ddb7/robotiq_s_model_control/src/robotiq_s_model_control/s_model_can_client.cpp#L33)):*
> ```cpp
>     ,driver_(driver)
> {
>     resp_header_.id = can_id + 0x580;
> ```

Document where `0x580` comes from?

---

*[robotiq_s_model_control/src/robotiq_s_model_control/s_model_can_client.cpp, line 211 at r3](https://reviewable.io:443/reviews/athackst/robotiq/1#-KXgzCaVFaaa86kC8mUX:-KXgzCaVFaaa86kC8mUY:b-k9ysid) ([raw file](https://github.com/athackst/robotiq/blob/6b5fc963f7b130fb793a8a31ae9538e50434ddb7/robotiq_s_model_control/src/robotiq_s_model_control/s_model_can_client.cpp#L211)):*
> ```cpp
>         can::Frame serial_request;
>         serial_request.id = can_id_+0x600;
>         serial_request.dlc = (unsigned char)8;
> ```

`static_cast<unsigned char>(8)`

---

*[robotiq_s_model_control/src/robotiq_s_model_control/s_model_can_client.cpp, line 215 at r3](https://reviewable.io:443/reviews/athackst/robotiq/1#-KXgzGOl2WtryEf9mjEB:-KXgzGOl2WtryEf9mjEC:b-k9yyfx) ([raw file](https://github.com/athackst/robotiq/blob/6b5fc963f7b130fb793a8a31ae9538e50434ddb7/robotiq_s_model_control/src/robotiq_s_model_control/s_model_can_client.cpp#L215)):*
> ```cpp
>         serial_request.is_rtr = 0;
>         serial_request.is_extended = 0;
>         serial_request.data.assign((unsigned char)0);
> ```

`static_cast<unsigned char>(0)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/athackst/robotiq/1)*

**Comment by hongkai-dai** [comment]
I left a few comments there, for style issue. If ROS style guide does not specify a rule, then I think we should follow google style guide?

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/athackst/robotiq/1#-:-KXh-B479rs2DU38B8ee:b-csby7e)*

**Comment by athackst** [comment]
Seems reasonable.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[robotiq_s_model_control/include/robotiq_s_model_control/s_model_hw_interface.h, line 56 at r3](https://reviewable.io:443/reviews/athackst/robotiq/1#-KXgyGrZIF4znA8-uW5C:-KXpSgT0S6OIy9ov63KR:bfw4uv1) ([raw file](https://github.com/athackst/robotiq/blob/6b5fc963f7b130fb793a8a31ae9538e50434ddb7/robotiq_s_model_control/include/robotiq_s_model_control/s_model_hw_interface.h#L56)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why using `boost::shared_ptr` instead of `std::shared_ptr`?
</blockquote></details>

because Indigo targets C++03 and not 11

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/athackst/robotiq/1#-:-KXw-ukcCbpGipZoScdL:b-a7b3ru)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 14 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/athackst/robotiq/1#-:-KY02S1cws1GdXI7X26P:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/athackst/robotiq/1)*

**Pull request merged**
